### PR TITLE
fixes #2091

### LINKED ISSUE #2091: Glitch Suppression default setting and spelling
Can we please change the default setting (Setup -> Device Settings -> preset Glitch Suppression) to "ON".

And I have found that in some parts of the code the spelling is incorrect:
[.../projects/acceptance-tests/src/VoiceAllocation.cpp](https://github.com/nonlinear-labs-dev/C15/blob/38f8e5aaaa2ec8a897e7eecf0306825f0490b019/projects/acceptance-tests/src/VoiceAllocation.cpp)
[.../client/presenters/DeviceSettings.java](https://github.com/nonlinear-labs-dev/C15/blob/381eb19f0c6b7f8c05f4ce1c834569921573d044/projects/NonMaps/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettings.java)
[.../client/world/overlay/html/setup/Setup.java](https://github.com/nonlinear-labs-dev/C15/blob/0c4dae0c29f3402d1be4743afb8e1506551a0b6b/projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.java)
[.../client/useCases/SystemSettings.java](https://github.com/nonlinear-labs-dev/C15/blob/381eb19f0c6b7f8c05f4ce1c834569921573d044/projects/NonMaps/src/main/java/com/nonlinearlabs/client/useCases/SystemSettings.java)
[.../client/world/overlay/html/setup/Setup.ui.xml](https://github.com/nonlinear-labs-dev/C15/blob/0c4dae0c29f3402d1be4743afb8e1506551a0b6b/projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/html/setup/Setup.ui.xml)

Maybe for the sake of consistency we should change to the correct spelling?

### PR DESCRIPTION
**Pull request by schlenkibus**
closes #2091

### CODE REVIEW

File: projects/NonMaps/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettings.java [hunk 1]
```diff
@@ -44,7 +44,7 @@
 	public Pedal pedal2 = new Pedal();
 	public Pedal pedal3 = new Pedal();
 	public Pedal pedal4 = new Pedal();
-	public PresetGlitchSurpression presetGlitchSurpession = new PresetGlitchSurpression();
+	public PresetGlitchSuppression presetGlitchSurpession = new PresetGlitchSuppression();
```
Comment (MatthiasSeeber) [inline projects/NonMaps/src/main/java/com/nonlinearlabs/client/presenters/DeviceSettings.java:47]: The public member name still is spelled `presetGlitchSurpession`
