### PR TITLE
Fix fade bugs

### LINKED ISSUE #2312: WebUI: Split Sound Tab: Verbessertes Layout der Split Point Valuefelder, senkrechter Strich bei Overlap == 0
Vorschlag:
WebUI Split Tab 1

### LINKED ISSUE #2313: WebUI: Split Sound Tab: Reiter und Button s.u.
- [x] Der Tab-Reiter sollt beim Öffnen des Split-Point-Editors selektiert bleiben (das gleiche gilt beim Layer für den Fade-Range-Editor). Wir sind ja noch im Sound-Tab.

- [x] Im Split-Point-Editor links vom Editor-Button einen "Enable Sync"-Button einfügen.

### LINKED ISSUE #2316: WebUI: Split Point Parameter Tab: "Enable Sync"-Button bitte rechts neben den Value setzen
Ähnlicher Abstand  wie links der Original-Value-Button

### LINKED ISSUE #2324: Statt "Sync Split", "Enable/Disable Sync" lieber "Link Splitpoints" und "Enable/Disable Link"
"Sync" ist nicht ganz treffend und kann im Audio-Bereich auch falsche Assoziationen auslösen.

### PR DESCRIPTION
**Pull request by schlenkibus**
closes #2324 
closes #2313 
closes #2312
closes #2316

### CODE REVIEW

File: projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/SyncParameterButton.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+import com.nonlinearlabs.client.world.Control;
+import com.nonlinearlabs.client.world.Position;
+import com.nonlinearlabs.client.world.overlay.OverlayLayout;
+import com.nonlinearlabs.client.world.overlay.SVGImage;
+
+public final class SyncParameterButton extends SVGImage {
+    
+    public SyncParameterButton(OverlayLayout parent) {
+		super(parent, "Sync_Disabled.svg", "Sync_Enabled.svg");
+        SetupModel.get().systemSettings.syncSplit.onChange(b -> {
```
Comment (hhoegelo) [inline projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/SyncParameterButton.java:17]: Consider registration at the DeviceSettingsProvider to invalidate the control and get the latest DeviceSettings presenter. Probably you'll have to enhance the presenter as well. 
Indeed, it is a bit nitpicking but we should try to follow the attempted data flow design (UseCase | Xml-Update) => DataModel => Presenter => UI.

Comment (schlenkibus) [reply projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/parameters/SyncParameterButton.java:17]: I appreciate your comment, and agree with you that new code should not use the DataModel directly.

**Review by hhoegelo — APPROVED** [review]

**Comment by schlenkibus** [comment]
I will merge this now as you approved the changes?!
