### PR TITLE
AudioEngine (Single) Glide Fix

### LINKED ISSUE #1719: AudioEngine - (Single) Mono Glide vs Unison Voices > 12
Glide Time seems to only affect one Voice Group - ParameterChanged and Recall.

The problem seems to arise with the current Key Event handling. Glides are only possible, when the Unison Index is zero, which would not be the case for the other Voice Group. The Test for starting a (Mono) Glide in the Poly Section needs another conditional variable (once and only first per Voice Group).

### PR DESCRIPTION
**Pull request by MatthiasSeeber**
closes #1719

### CODE REVIEW

File: projects/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp [hunk 1]
```diff
@@ -1165,6 +1165,7 @@ uint32_t dsp_host_dual::onSettingToneToggle()
 
 void dsp_host_dual::render()
 {
+  m_sample_counter += SAMPLE_COUNT;
```
Comment (MatthiasSeeber) [inline projects/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp]: I originally removed this line because it was present twice and thought, counting the sample at the end would make more sense. However, it then would not be counted if the Engine is muted.
Now, it always counts and is present only once, at the start.
