### PR TITLE
closes #2435

### LINKED ISSUE #2435: BOLED: Crash bei Preset Inc/Dec in einer leeren Bank (s.u.) + "New Bank" inkonsistent
- [x] Schritte zum Crash:
- Leere Bank erzeugen
- "Bank" ggf. ausschalten
- "Inc" oder "Dec" drücken
=> Crash nach kurzer Verzögerung (... eine Rekursion mit Stack Overflow, verursacht durch einen Nullpointer... ;-) )

- [x] Übrigens: eine neue Bank heisst im BOLED "Untitled Bank" (mit spitzen Klammern), während eine neue Bank in der WebUI "New Bank" heisst und sich sinnvollerweise auch gleich ein Rename-Dialog öffnet. Bitte im BOLED so wie in der WebUI, d.h. mit Rename-Screen nach dem Erzeugen der Bank.

### PR DESCRIPTION
**Pull request by schlenkibus**

### CODE REVIEW

File: projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.cpp [hunk 1]
```diff
@@ -128,10 +128,9 @@ void BankEditButtonMenu::newBank()
   newBank->setX(transaction, to_string(pos.first));
   newBank->setY(transaction, to_string(pos.second));
   pm->selectBank(transaction, newBank->getUuid());
-
-  Application::get().getHWUI()->undoableSetFocusAndMode(transaction, FocusAndMode(UIFocus::Presets, UIMode::Select));
-
-  auto layout = new RenameBankLayout(transaction);
+  auto layout = new RenameBankLayout(transaction, [](auto transaction) {
```
Comment (hhoegelo) [inline projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.cpp:131]: I wonder if we we could avoid the lambda, the commit callback etc, if we just first set the focus and mode here in line 131, then install the RenameBankLayout. Then, after renaming, the overlay layout will be closed and the intended FocusAndMode would already be there - but it is absolutely possible, that I am missing something here.

Comment (schlenkibus) [reply projects/epc/playground/src/proxies/hwui/panel-unit/boled/preset-screens/controls/BankEditButtonMenu.cpp:131]: "DelayedJob m_setupJob;" is the job responsible dispatching the focusAndMode Changes to the Panel/Baseunit. It being async, the overlay will be installed, and then removed from within OLEDproxy::reset(LayoutPtr t)
  
I would prefer not change the behavior of the OLEDProxy class and rather roll with the solution I proposed.

**Review by hhoegelo — APPROVED** [review]
