### PR TITLE
HWUI misc fixes

### LINKED ISSUE #1187: Mono Glide should be modulateable-Parameter

### LINKED ISSUE #1188: Unison + Layer
- [ ] Unison Voices should appear "Global" in Layer mode
- [ ] Other Unison Parameters should be per voicegroup

### LINKED ISSUE #1189: Mono + Layer
Mono Parameters will be global (from vg I) and mono glide will be per voice group

### LINKED ISSUE #1198: ParameterChangedMsg issues
- [x] Split Point: should be modulateable parameter and send modulateable parameter message (currently, it is unmodulateable and sends unmodulateable parameter message)
- [x] Mono Glide: same thing
- [x] Voice Group: Volume, Tune and To_FX should be modulateable parameters and should send modulateable parameter messages (To_FX should be implemented - possibly besides Output Mixer Level)
- [x] Feedback Mixer: new Parameters (see ParameterList_1.7B.ods) Osc, Osc_Source, Comb_Source, SFV_Source, FX_Source should also be implemented (as modulateable parameters)

- [x] Remove Locks from Parameter / Preset Messages

### LINKED ISSUE #1205: Active Overview broken
Way too many parameter LED are lit up, compare to previous version, before moving to LibparameterDB

### LINKED ISSUE #1213: Sound-Screen: "Convert To.."-Menü durch Druck auf "Sound"-Button wieder schliessen (und im Screen bleiben)
Bisher lässt sich das Menü nicht wieder schliessen. Mit dem Sound-Button wäre es möglich, aber man müsste dabei im Screen bleiben. Wenn das Menü nicht offen ist, verlässt man den Screen mit dem Sound-Button.

(Alternative: Menü mit 3 States: "Split", "Layer" und Menü=Aus)

### PR DESCRIPTION
**Pull request by schlenkibus**
fixes #1188 
fixes #1187 
fixes #1205 
fixes #1189 
fixes #1198 
fixes #1213

### CODE REVIEW

File: playground/src/groups/UnisonGroup.cpp [hunk 1]
```diff
@@ -61,6 +62,26 @@ namespace Detail
         : tParameter(args...){};
 
     DFBLayout *createLayout(FocusAndMode focusAndMode) const override
+    {
```
Comment (hhoegelo) [inline playground/src/groups/UnisonGroup.cpp]: I don't think its worth another template class here: There is actually nothing shared between both users - only the dispatching code that tries to separate both classes again.
