### PR TITLE
fixes hw amount boolean slider

### LINKED ISSUE #1588: WebUI: Die HW Amounts werden, auch wenn sie Schalter sind, in der Bauchbinde als kontinuierlich dargestellt/bedient.

### PR DESCRIPTION
**Pull request by schlenkibus**
closes #1588

### CODE REVIEW

File: projects/NonMaps/src/main/java/com/nonlinearlabs/client/dataModel/ValueUpdater.java [hunk 1]
```diff
@@ -18,6 +18,12 @@ public void doUpdate() {
 		String bipolar = getChildText(root, "bipolar");
 		String scaling = getChildText(root, "scaling");
 		String defaultValue = getChildText(root, "default");
+		String bool = getChildText(root, "boolean");
+
+		if(!bool.isEmpty()) {
```
Comment (hhoegelo) [inline projects/NonMaps/src/main/java/com/nonlinearlabs/client/dataModel/ValueUpdater.java:23]: why is the number of steps in coarse/fineDenominator not sufficient?

Comment (schlenkibus) [reply projects/NonMaps/src/main/java/com/nonlinearlabs/client/dataModel/ValueUpdater.java:23]: The Scale Converter of Hardware Amounts is not boolean if non returning, checking for steps is not sufficent for these parameters
