### PR TITLE
Boled: fix animation for sound-edit convert and copy-fx entries

### LINKED ISSUE #3544: BOLED: Sound Edit Menü: Es fehlen Animationen für die Convert- und Copy-Aktionen und Enter-Pfeile für die Copy-Zeilen.

### PR DESCRIPTION
**Pull request by schlenkibus**
fixup all current animated sound-edit-menu items to show the animation before closing/changing the screen, added return symbol at the end of the lines of copy FX I/II items, closes #3544

### CODE REVIEW

**Review by MatthiasSeeber — APPROVED** [review]

**Comment by schlenkibus** [comment]
TODO: check if we can circumvent the unlocking by for example selecting a parameter before the animation completes

**Comment by davidm2894** [comment]
> TODO: check if we can circumvent the unlocking by for example selecting a parameter before the animation completes

if you select a parameter before the animation completes, the screen changes but the actual action (converting for example) has already happened by then.

However, I'm not sure if it's that what you wanted to know.

**Comment by schlenkibus** [comment]
> > TODO: check if we can circumvent the unlocking by for example selecting a parameter before the animation completes
> 
> if you select a parameter before the animation completes, the screen changes but the actual action (converting for example) has already happened by then.
> 
> However, I'm not sure if it's that what you wanted to know.

I suspect that the DescriptiveLayouts won't behave after the steps you describe. For example the sound type won't be properly reflected in the sound-layout when it changes. 

This should happen because the animation finish callback won't ever be called and the condition-registry keeps 'locked' meaning won't propagate changes.

File: projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/ConvertToSoundTypeItem.cpp [hunk 1]
```diff
@@ -79,11 +87,13 @@ ConvertToSoundTypeItemWithFX::ConvertToSoundTypeItemWithFX(const Rect& rect, Sou
                                   default:
                                     break;
                                 }
-
+                              }),
+                          OneShotTypes::FinishCB(
+                              []()
+                              {
+                                ConditionRegistry::get().unlock();
```
Comment (hhoegelo) [inline projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/ConvertToSoundTypeItem.cpp:94]: Is it correct that you release the lock in this class before setFocusAndMode, whereas you do it vice versa in ConvertToSoundTypeItem?

File: projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/ConvertToSoundTypeItem.cpp [hunk 2]
```diff
@@ -47,21 +52,24 @@ ConvertToSoundTypeItem::ConvertToSoundTypeItem(const Rect& rect, SoundType toTyp
...
 }
 
-
 ConvertToSoundTypeItemWithFX::ConvertToSoundTypeItemWithFX(const Rect& rect, SoundType convertTo)
 
     : AnimatedGenericItem(nltools::string::concat("Convert to ", toString(convertTo), " (FX I only)"), rect,
                           OneShotTypes::StartCB(
                               [=]
                               {
+                                ConditionRegistry::get().lock();
```
Comment (hhoegelo) [inline projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/ConvertToSoundTypeItem.cpp:72]: I think we have a serious problem with AnimatedGenericItem:
If you manage to destroy the item while the animation is still running (for example by pressing some button fast enough), the finishedCB will never be executed. This might be ok, if the finishedCB would only trigger actions, but if - like here - counters are incremented/decremented, this will cause irreparable invalid state (lock will be held forever).
I see three possible solutions:
- avoid mandatory actions in the finishCB
- add a 'catchAllCB' that is unconditionally executed in the AnimatedGenericItem destructor  
- have an object representing the locked state (will release the lock in its destructor) and capture this object in the finishedCB-lambda: ```OneShotTypes::FinishCB([lock = ConditionRegistry::get().createLock()](){ ...})```. Once the AnimatedGenericItem gets destroyed, it will destroy its finishedCB and thus release the lock.

Comment (schlenkibus) [reply projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/menus/items/ConvertToSoundTypeItem.cpp:72]: i decided to add a optional catchAllCB to the animator which gets executed when the animator is destroyed

**Review by hhoegelo — APPROVED** [review]
