### PR TITLE
Remove WiFi polling, store WiFi status on Disk now. Removed usage of …

### LINKED ISSUE #2716: EPC wifi 2 finalize
Assertions:
10i3 will always have an WiFi-Stick connected
if the connected BBB has an WiFi Stick the NetworkSSID will be <SSID>_BBB

to fix:
- [ ] WiFi enabled returns wrong information on epc2 (#2718 does not seem to fix it)

### PR DESCRIPTION
**Pull request by schlenkibus**
…SSH to communicate with the BBB -> now uses nltools. Moved BBB AP-Toggle into scripts that live on the BBB. Change initial status of EPCWifi to std::optional to distinguish between initial-status and explicit-status

closes #2716

### CODE REVIEW

File: projects/bbb/bridge/src/io/WiFiManager.cpp [hunk 1]
```diff
@@ -2,25 +2,34 @@
...
   nltools::msg::receive<nltools::msg::WiFi::SetWiFiSSIDMessage>(nltools::msg::EndPoint::BeagleBone,
                                                                 [this](const auto& msg) {
+                                                                  nltools::Log::notify("got ssid:", msg.m_ssid.get());
                                                                   m_lastSeenSSID = msg.m_ssid.get();
                                                                   saveConfig();
                                                                 });
 
   nltools::msg::receive<nltools::msg::WiFi::SetWiFiPasswordMessage>(nltools::msg::EndPoint::BeagleBone,
                                                                     [this](const auto& msg) {
+                                                                      nltools::Log::notify("got pw:", msg.m_password.get());
```
Comment (schlenkibus) [inline projects/bbb/bridge/src/io/WiFiManager.cpp:18]: Remove logs, if no longer needed

File: projects/bbb/bridge/src/io/WiFiManager.cpp [hunk 2]
```diff
@@ -62,10 +71,32 @@ void WiFiManager::scheduleRestart()
   nltools::Log::info(__FILE__, __FUNCTION__, "schedule Restart!");
   auto thread = std::thread([]() {
     if(system("systemctl restart accesspoint"))
-      nltools::Log::warning("Could not restart WiFi!");
+      nltools::Log::error("Could not restart WiFi!");
     else
-      nltools::Log::info(__FILE__, __FUNCTION__, "WiFi Restarted!");
+      nltools::Log::notify(__FILE__, __FUNCTION__, "WiFi Restarted!");
```
Comment (schlenkibus) [inline projects/bbb/bridge/src/io/WiFiManager.cpp:76]: remove log, if not needed

File: projects/bbb/bridge/src/io/WiFiManager.cpp [hunk 3]
```diff
@@ -62,10 +69,28 @@ void WiFiManager::scheduleRestart()
   nltools::Log::info(__FILE__, __FUNCTION__, "schedule Restart!");
   auto thread = std::thread([]() {
     if(system("systemctl restart accesspoint"))
-      nltools::Log::warning("Could not restart WiFi!");
-    else
-      nltools::Log::info(__FILE__, __FUNCTION__, "WiFi Restarted!");
+      nltools::Log::error("Could not restart WiFi!");
```
Comment (hhoegelo) [inline projects/bbb/bridge/src/io/WiFiManager.cpp:72]: Consider using nltools AsyncCommandLine instead of detached threads

File: projects/epc/playground/src/device-settings/WifiSetting.cpp [hunk 4]
```diff
@@ -2,125 +2,69 @@
...
+  nltools::msg::onConnectionEstablished(nltools::msg::EndPoint::BeagleBone, [this](){
+     m_connectionToBBBEstablished = true;
+     setupBBBWifiIfBBBConnectedAndSettingLoaded();
+  });
 }
 
 bool WifiSetting::set(tEnum m)
 {
-  auto ret = super::set(m);
+  auto didChange = super::set(m);
```
Comment (hhoegelo) [inline projects/epc/playground/src/device-settings/WifiSetting.cpp:22]: didChange: name is misleading

**Review by hhoegelo — APPROVED** [review]
