### PR TITLE
fixup parametercarousel crash

### LINKED ISSUE #3495: Boled: crash if softbutton 4 is pressed in Parameter-Layouts with only one parameter (and no carousel)

### PR DESCRIPTION
**Pull request by schlenkibus**
fixup parametercarousel to no longer crash on turn and antiTurn when no other parameters are in the carousel, closes #3495

### CODE REVIEW

File: projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterCarousel.cpp [hunk 1]
```diff
@@ -284,13 +290,17 @@ void ParameterCarousel::setupChildControlsThatDontFit(Parameter* selectedParamet
   }
 }
 
-int ParameterCarousel::firstParameterIDOfCarousel() const
+std::optional<int> ParameterCarousel::firstParameterIDOfCarousel() const
```
Comment (MatthiasSeeber) [inline projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/ParameterCarousel.cpp:293]: I get a compilation error suggesting to include `<optional>` in the header.

**Review by MatthiasSeeber — CHANGES_REQUESTED** [review]

**Review by MatthiasSeeber — APPROVED** [review]
