### PR TITLE
HWUI minor fixes: closes #3385

### LINKED ISSUE #3385: HWUI: minor fixups for soled ribbon displays and scale offsets
- [x] reduce distance between the blocks of 4 scale-offsets by one pixel (bottom y position of the whole block should not change) 
- [x] remove the pedal symbol from the Macro-String in the SOLED play-mode, left align the standalone pedal-indication
- [x] remove the pedal symbol from the Macro-String in the SOLED edit-mode, left align the standalone pedal-indication
- [x] remove the space between the Circled Macro Symbol and the given name (if there is any) -> undo
- [ ] move the new ribbon selector one more pixel to the right
- [x] remove undocumented (and supposedly unused) display feature that showed which other MCs the selected ribbon is modulating (for returning ribbons only)

### PR DESCRIPTION
**Pull request by schlenkibus**
removed underused and confusing MCRouting indication
split PedalIndication into own control
remove pedal indication from hwui mc text
reduce distance between scale-offset blocks
move new ribbon selector more to the right

closes #3385

### CODE REVIEW

File: projects/epc/playground/src/proxies/hwui/base-unit/soled/PlayModeLayout.cpp [hunk 1]
```diff
@@ -2,16 +2,57 @@
...
+}
+
+void PlayModeLayout::createUpperLabels()
+{
+  remove(m_pedalSymbol);
+  m_pedalSymbol = nullptr;
+  remove(m_ribbonLabel);
+  m_ribbonLabel = nullptr;
+
+  if(isPedalMappedToCurrentUpperRibbon())
```
[the remark this answers is not in the document]
Comment (schlenkibus) [reply projects/epc/playground/src/proxies/hwui/base-unit/soled/PlayModeLayout.cpp:46]: remove(std::exchange(m_foo, addControl(new MCRoutings(HardwareSourcesGroup::getLowerRibbon2ParameterID(), Rect(104, 17, 8, 12)))));

File: projects/epc/playground/src/proxies/hwui/base-unit/soled/PlayOrEditModeLayout.cpp [hunk 2]
```diff
@@ -26,23 +28,90 @@ PlayOrEditModeLayout::PlayOrEditModeLayout()
...
 
-void PlayOrEditModeLayout::onParameterSelectionChanged(const Parameter* old, Parameter* newP)
+void PlayOrEditModeLayout::createLowerLabels()
+{
+  remove(m_pedalIndicationLower);
+  m_pedalIndicationLower = nullptr;
+  remove(m_ribbonLabelLower);
+  m_ribbonLabelLower = nullptr;
+
+  if(isPedalMappedToCurrentLowerRibbon())
```
Comment (hhoegelo) [inline projects/epc/playground/src/proxies/hwui/base-unit/soled/PlayOrEditModeLayout.cpp:58]: pls try to reduce duplication

File: projects/epc/playground/src/proxies/hwui/base-unit/soled/PlayOrEditModeLayout.cpp [hunk 3]
```diff
@@ -26,23 +28,90 @@ PlayOrEditModeLayout::PlayOrEditModeLayout()
...
+  if(is1_2Ribbons)
+  {
+    RibbonParameter* param = eb->findAndCastParameterByID<RibbonParameter>({ C15::PID::Ribbon_1, VoiceGroup::Global });
+    return param->isMCAssignedToThisAlsoAssignedToAnyPedal();
+  }
+  else
+  {
+    RibbonParameter* param = eb->findAndCastParameterByID<RibbonParameter>({ C15::PID::Ribbon_3, VoiceGroup::Global });
+    return param->isMCAssignedToThisAlsoAssignedToAnyPedal();
+  }
```
Comment (hhoegelo) [inline projects/epc/playground/src/proxies/hwui/base-unit/soled/PlayOrEditModeLayout.cpp:111]:
```suggestion
  RibbonParameter* param = eb->findAndCastParameterByID<RibbonParameter>({ is1_2Ribbons ? C15::PID::Ribbon_1 : C15::PID::Ribbon_3, VoiceGroup::Global });
  return param->isMCAssignedToThisAlsoAssignedToAnyPedal();
```

**Review by hhoegelo — APPROVED** [review]
